#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p RaspiJoy
cd RaspiJoy
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "raspi0123joy" > strings/0x409/serialnumber
echo "Sevval Mehder" > strings/0x409/manufacturer
echo "RaspiJoy Joystick" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower
# Add functions here
# Functions -> protocol & subclass & report_length & report_desc
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol       
echo 1 > functions/hid.usb0/subclass       # boot interface subclass
echo 8 > functions/hid.usb0/report_length  
echo -ne \\x05\\x01\\x09\\x04\\xa1\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x08\\x15\\x00\\x25\\x01\\x95\\x08\\x75\\x01\\x81\\x02\\x05\\x01\\x09\\x30\\x09\\x31\\x09\\x32\\x09\\x33\\x15\\x81\\x25\\x7f\\x75\\x08\\x95\\x04\\x81\\x02\\xc0\\xc0 > functions/hid.usb0/report_desc
ln -s functions/hid.usb0 configs/c.1/
# End functions
ls /sys/class/udc > UDC